services:
  redis:
    image: redis:7

  web:
    build: .
    command: gunicorn app:app -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - uploads:/app/tmp/uploads
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A celery_app.celery worker --loglevel=info
    env_file:
      - .env
    volumes:
      - uploads:/app/tmp/uploads
    depends_on:
      - redis
volumes:
  uploads: