version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build:
      context: /www/wwwroot/HBD_Dashboard/backend
      dockerfile: Dockerfile
    command: gunicorn app:app -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - /www/wwwroot/HBD_Dashboard/backend/.env
    volumes:
      - /www/wwwroot/HBD_Dashboard/backend/tmp:/app/tmp
    depends_on:
      - redis

  worker:
    build:
      context: /www/wwwroot/HBD_Dashboard/backend
      dockerfile: Dockerfile
    command: celery -A celery_app.celery worker --loglevel=info
    env_file:
      - /www/wwwroot/HBD_Dashboard/backend/.env
    volumes:
      - /www/wwwroot/HBD_Dashboard/backend/tmp:/app/tmp
    depends_on:
      - redis
